on: [push]

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:

      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_stack: 'WebsiteStack'
          cdk_args: '--require-approval never --parameters domains="stealy.link,www.stealy.link" --parameters certificateArn=arn:aws:acm:ap-southeast-2:645549479777:certificate/864eb311-e399-4651-984e-0fdf424a2c57 --parameters hostedZoneId=Z044956514TIJL09PO03H'
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'ap-southeast-2'
